### ISSUE TITLE
Suggestion: Auto group sort

### ISSUE THREAD

**Issue by RadNotRed** [E-boi/Better-Friends-List#1]
Similar to Devilbro's PIN Dms plugin for BD, add an auto group sort 

![DiscordCanary_LxDfpOO9y1](https://user-images.githubusercontent.com/80015713/115453428-a0add500-a1ed-11eb-9320-202d3c9f3bbc.png)

**Comment by E-boi** [comment]
it would be nice but this plugin mainly aiming at the friends list that you get when you first start discord
